INSERT INTO EQUIPE (NOME) VALUES ('EMAD-1A');
INSERT INTO EQUIPE (NOME) VALUES ('EMAD-1B');
INSERT INTO EQUIPE (NOME) VALUES ('EMAD-2A');
INSERT INTO EQUIPE (NOME) VALUES ('EMAD-2B');

INSERT INTO USUARIO (EMAIL, NOME, SENHA, ROLES)
VALUES ('admin@teste.com', 'Administrador', 'admin123', 'ADMIN');

INSERT INTO VEICULO (PLACA, MODELO, KM_ATUAL) VALUES
('IWT 4B59', 'SPIN', 0.0),
('IYF 7400', 'SPIN', 0.0),
('IWT 4B61', 'SPIN', 0.0),

