package com.hps.vilanova.model.enums;

public enum StatusBaixa {
    OBITO_HOSPITALAR,
    REINTERNACAO_HOSPITALAR,
    ILPI,
    SEM_REDE_APOIO,
    MUDANCA_ENDERECO,
    INTERNACAO_HOSPITALAR,
    CANCELAMENTO_SOLICITANTE,
    RECUSA_PACIENTE_FAMILIAR,
    NAO_LOCALIZADO,
    OBITO_DOMICILIAR,
    SITUACOES_ESPECIFICAS
}
