package com.hps.vilanova.model.enums;

public enum StatusSala {
    AGUARDANDO_CONTATO,
    AGUARDANDO_DISCUSSAO_EMADS,
    AGUARDANDO_PRIMEIRA_VD,
    AGUARDANDO_ALTA_HOSPITALAR,
    SITUACOES_ESPECIFICAS,
    OBITO_HOSPITALAR,
    REINTERNACAO_HOSPITALAR,
    ILPI,
    SEM_REDE_APOIO,
    MUDANCA_ENDERECO,
    INTERNACAO_HOSPITALAR,
    CANCELAMENTO_SOLICITANTE,
    RECUSA_PACIENTE_FAMILIAR,
    NAO_LOCALIZADO,
    OBITO_DOMICILIAR
}
