package com.hps.vilanova.model.enums;

public enum StatusVisita {
    CONSULTORIA_AGENDADA,
    CONSULTORIA_A_CAMINHO,
    CONSULTORIA_CORRIDA_FINALIZADA,
    CONSULTORIA_INICIADA,
    CONSULTORIA_REALIZADA,
    CONSULTORIA_RELATORIO,
    CONSULTORIA_FINALIZADA,
    AGENDADA,
    A_CAMINHO,
    CORRIDA_FINALIZADA,
    INICIADA,
    REALIZADA,
    RELATORIO,
    ENCERRADA;
}
